// AUTO-GENERATED by scripts/update-pricing.ts — do not edit by hand
// Source: https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json
// Updated: 2026-06-29

export interface ModelPricing {
  inputCostPerToken: number;   // USD per token
  outputCostPerToken: number;  // USD per token
}

export const ANTHROPIC_PRICING: Record<string, ModelPricing> = {
  'claude-3-7-sonnet-20250219':                  { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
  'claude-3-haiku-20240307':                     { inputCostPerToken: 2.5e-7, outputCostPerToken: 0.00000125 },
  'claude-3-opus-20240229':                      { inputCostPerToken: 0.000015, outputCostPerToken: 0.000075 },
  'claude-4-opus-20250514':                      { inputCostPerToken: 0.000015, outputCostPerToken: 0.000075 },
  'claude-4-sonnet-20250514':                    { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
  'claude-fable-5':                              { inputCostPerToken: 0.00001, outputCostPerToken: 0.00005 },
  'claude-haiku-4-5':                            { inputCostPerToken: 0.000001, outputCostPerToken: 0.000005 },
  'claude-haiku-4-5-20251001':                   { inputCostPerToken: 0.000001, outputCostPerToken: 0.000005 },
  'claude-opus-4-1':                             { inputCostPerToken: 0.000015, outputCostPerToken: 0.000075 },
  'claude-opus-4-1-20250805':                    { inputCostPerToken: 0.000015, outputCostPerToken: 0.000075 },
  'claude-opus-4-20250514':                      { inputCostPerToken: 0.000015, outputCostPerToken: 0.000075 },
  'claude-opus-4-5':                             { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-opus-4-5-20251101':                    { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-opus-4-6':                             { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-opus-4-6-20260205':                    { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-opus-4-7':                             { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-opus-4-7-20260416':                    { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-opus-4-8':                             { inputCostPerToken: 0.000005, outputCostPerToken: 0.000025 },
  'claude-sonnet-4-20250514':                    { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
  'claude-sonnet-4-5':                           { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
  'claude-sonnet-4-5-20250929':                  { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
  'claude-sonnet-4-5-20250929-v1:0':             { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
  'claude-sonnet-4-6':                           { inputCostPerToken: 0.000003, outputCostPerToken: 0.000015 },
};
