#!/usr/bin/env tsx
/**
 * Fetches Anthropic model pricing from the LiteLLM community pricing registry and
 * regenerates src/pricing/anthropic.ts.
 *
 * Exits non-zero if the source schema has changed in a way that breaks extraction,
 * so CI fails loudly rather than committing a silently corrupt pricing table.
 *
 * Usage:
 *   npm run update-pricing
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE_URL =
  'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json';
const OUTPUT_PATH = resolve(import.meta.dirname, '../src/pricing/anthropic.ts');

interface LiteLLMEntry {
  input_cost_per_token?: unknown;
  output_cost_per_token?: unknown;
  [key: string]: unknown;
}

interface ModelPricing {
  inputCostPerToken: number;
  outputCostPerToken: number;
}

function validate(model: string, entry: LiteLLMEntry): ModelPricing {
  const input = entry.input_cost_per_token;
  const output = entry.output_cost_per_token;

  if (typeof input !== 'number' || input <= 0) {
    throw new Error(
      `Schema validation failed for "${model}": input_cost_per_token is ${JSON.stringify(input)}`
    );
  }
  if (typeof output !== 'number' || output <= 0) {
    throw new Error(
      `Schema validation failed for "${model}": output_cost_per_token is ${JSON.stringify(output)}`
    );
  }

  return { inputCostPerToken: input, outputCostPerToken: output };
}

function parseCurrent(): Record<string, ModelPricing> {
  if (!existsSync(OUTPUT_PATH)) return {};
  const src = readFileSync(OUTPUT_PATH, 'utf8');
  const result: Record<string, ModelPricing> = {};
  const re = /'([^']+)':\s*\{\s*inputCostPerToken:\s*([\d.e-]+),\s*outputCostPerToken:\s*([\d.e-]+)/g;
  for (const m of src.matchAll(re)) {
    result[m[1]] = { inputCostPerToken: parseFloat(m[2]), outputCostPerToken: parseFloat(m[3]) };
  }
  return result;
}

function summariseDiff(
  before: Record<string, ModelPricing>,
  after: Record<string, ModelPricing>
): string {
  const lines: string[] = [];

  for (const model of Object.keys(after)) {
    if (!before[model]) {
      lines.push(`+ ${model} added (in: $${after[model].inputCostPerToken}, out: $${after[model].outputCostPerToken})`);
    } else {
      const b = before[model];
      const a = after[model];
      if (b.inputCostPerToken !== a.inputCostPerToken || b.outputCostPerToken !== a.outputCostPerToken) {
        lines.push(
          `~ ${model} changed (in: $${b.inputCostPerToken} → $${a.inputCostPerToken}, out: $${b.outputCostPerToken} → $${a.outputCostPerToken})`
        );
      }
    }
  }
  for (const model of Object.keys(before)) {
    if (!after[model]) lines.push(`- ${model} removed`);
  }

  return lines.length ? lines.join('\n') : 'No pricing changes detected.';
}

function generateFile(pricing: Record<string, ModelPricing>, date: string): string {
  const entries = Object.entries(pricing)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([model, p]) => {
      const pad = Math.max(0, 44 - model.length);
      return `  '${model}':${' '.repeat(pad)}{ inputCostPerToken: ${p.inputCostPerToken}, outputCostPerToken: ${p.outputCostPerToken} },`;
    })
    .join('\n');

  return `// AUTO-GENERATED by scripts/update-pricing.ts — do not edit by hand
// Source: ${SOURCE_URL}
// Updated: ${date}

export interface ModelPricing {
  inputCostPerToken: number;   // USD per token
  outputCostPerToken: number;  // USD per token
}

export const ANTHROPIC_PRICING: Record<string, ModelPricing> = {
${entries}
};
`;
}

async function main() {
  console.log(`Fetching pricing data from LiteLLM...`);
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`Fetch failed: ${res.status} ${res.statusText}`);

  const raw = (await res.json()) as Record<string, LiteLLMEntry>;

  const pricing: Record<string, ModelPricing> = {};
  const errors: string[] = [];

  for (const [model, entry] of Object.entries(raw)) {
    if (!/^claude-/i.test(model)) continue;
    // Skip models with no pricing (free/internal entries)
    if (entry.input_cost_per_token == null || entry.output_cost_per_token == null) continue;
    try {
      pricing[model] = validate(model, entry);
    } catch (err) {
      errors.push(String(err));
    }
  }

  if (errors.length) {
    console.error('Schema validation errors:');
    errors.forEach((e) => console.error(` ${e}`));
    process.exit(1);
  }

  const before = parseCurrent();
  const date = new Date().toISOString().slice(0, 10);
  const diff = summariseDiff(before, pricing);

  console.log('\nPricing diff:');
  console.log(diff);

  writeFileSync(OUTPUT_PATH, generateFile(pricing, date), 'utf8');
  console.log(`\nWrote ${Object.keys(pricing).length} models to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
